name = "openai-image-proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && ~/.cargo/bin/worker-build --release --no-opt"

[vars]
# Deployment configuration
DEPLOYMENT_MODE = "official"  # This is the official hosted instance
REQUIRE_OWN_OPENAI_KEY = "false"

# OAuth Configuration
GITHUB_CLIENT_ID = "Ov23liVZ3rECA6jltb1f"
GOOGLE_CLIENT_ID = "720004930052-n4tdei4ua9shd2hqr1f6udmg5ijvj25j.apps.googleusercontent.com"
GOOGLE_DEVICE_CLIENT_ID = "720004930052-uiv67gpm9rpgj9ku2lq6ie4oiplrle6f.apps.googleusercontent.com"

# Service URLs
SERVICE_URL = "https://openai-image-proxy.guitaripod.workers.dev"
API_BASE_URL = "https://openai-image-proxy.guitaripod.workers.dev"

# Environment
ENVIRONMENT = "production"

# OpenAI API key will be stored as a secret
# Run: npx wrangler secret put OPENAI_API_KEY

[[d1_databases]]
binding = "DB"
database_name = "openai-image-proxy"
database_id = "e77acafe-2e95-41e7-97a4-df05de7a5f9b"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "openai-image-proxy-images"

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development" }